const c=document.getElementById('game'),g=c.getContext('2d'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),ov=document.getElementById('overlay'),ovT=document.getElementById('ovTitle'),ovX=document.getElementById('ovText'),btn=document.getElementById('startBtn');
const ground=340;let dino,obs,score,best=+(localStorage.getItem('arcade_best_dino')||0),running=false,last=0,nextSpawn=0,speed=300;bestEl.textContent=best;
function reset(){dino={x:95,y:ground-56,w:52,h:56,vy:0,on:true};obs=[];score=0;speed=300;nextSpawn=.9;scoreEl.textContent=0;draw()}
function start(){if(!running){running=true;last=performance.now();ov.classList.add('hidden');requestAnimationFrame(loop)}}
function restart(){running=false;reset();start()}
function jump(){if(!running)start();if(dino.on){dino.vy=-690;dino.on=false}}
function over(){running=false;best=Math.max(best,Math.floor(score));localStorage.setItem('arcade_best_dino',best);bestEl.textContent=best;ovT.textContent='Game Over';ovX.textContent=`Điểm: ${Math.floor(score)} • Kỷ lục: ${best}`;btn.textContent='Chơi lại';ov.classList.remove('hidden')}
function hit(a,b){return a.x+8<b.x+b.w&&a.x+a.w-8>b.x&&a.y+8<b.y+b.h&&a.y+a.h>b.y+5}
function loop(t){if(!running)return;let dt=Math.min(.033,(t-last)/1000);last=t;score+=dt*10;scoreEl.textContent=Math.floor(score);speed=Math.min(580,300+score*1.8);dino.vy+=1900*dt;dino.y+=dino.vy*dt;if(dino.y>=ground-dino.h){dino.y=ground-dino.h;dino.vy=0;dino.on=true}nextSpawn-=dt;if(nextSpawn<=0){let tall=Math.random()>.55;obs.push({x:c.width+30,y:ground-(tall?70:45),w:tall?34:30,h:tall?70:45});nextSpawn=.85+Math.random()*1.05}obs.forEach(o=>o.x-=speed*dt);obs=obs.filter(o=>o.x+o.w>-20);for(const o of obs)if(hit(dino,o))return over();draw();requestAnimationFrame(loop)}
function draw(){g.fillStyle='#f6f0df';g.fillRect(0,0,c.width,c.height);g.fillStyle='#d7d0be';for(let i=0;i<9;i++){let x=(i*123+40)%c.width;g.fillRect(x,80+(i%3)*35,25,3)}g.fillStyle='#7d7769';g.fillRect(0,ground,c.width,4);g.fillStyle='#5c574d';for(const o of obs){g.fillRect(o.x,o.y,o.w,o.h);g.fillRect(o.x-8,o.y+18,8,12);g.fillRect(o.x+o.w,o.y+30,8,12)}g.fillStyle='#2e7d4f';g.beginPath();g.roundRect(dino.x,dino.y,dino.w,dino.h,10);g.fill();g.fillStyle='#173d29';g.fillRect(dino.x+34,dino.y+11,5,5);g.fillRect(dino.x+11,dino.y+dino.h-7,12,7);g.fillRect(dino.x+32,dino.y+dino.h-7,12,7)}
document.addEventListener('keydown',e=>{if(e.code==='Space'||e.key==='ArrowUp'){e.preventDefault();jump()}if(e.key.toLowerCase()==='r')restart()},{passive:false});c.addEventListener('pointerdown',e=>{e.preventDefault();jump()});btn.onclick=()=>ovT.textContent==='Game Over'?restart():start();reset();
