
const c = document.getElementById('game'), g = c.getContext('2d');
const scoreEl = document.getElementById('score'), speedEl = document.getElementById('speed'), bestEl = document.getElementById('best');
const ov = document.getElementById('overlay'), ovT = document.getElementById('ovTitle'), ovX = document.getElementById('ovText'), btn = document.getElementById('startBtn');
const LANES=4, roadX=100, roadW=520, laneW=roadW/LANES, MIN_Y=420, MAX_Y=590, STEP_Y=28;
let player, obstacles, distance, best=+(localStorage.getItem('arcade_best_racing')||0), running=false,last=0,spawnT=0,roadOffset=0,worldSpeed=270;
bestEl.textContent=best;
function skin(){ return window.ArcadeSkins?.get('racing')?.colors || { player:'#ff3b30', glass:'#7ee7ff', light:'#ffe86b' }; }
function laneX(lane,w=72){ return roadX+lane*laneW+(laneW-w)/2; }
function reset(){ player={lane:1,x:laneX(1,72),targetX:laneX(1,72),y:590,targetY:590,w:72,h:110}; obstacles=[]; distance=0; spawnT=.5; worldSpeed=270; roadOffset=0; scoreEl.textContent=0; speedEl.textContent='1.0×'; draw(); }
function start(){ if(running) return; running=true; window.ArcadeAudio?.startMusic(); last=performance.now(); ov.classList.add('hidden'); requestAnimationFrame(loop); }
function restart(){ running=false; reset(); start(); }
function driveHoriz(d){ if(!running) start(); const next=Math.max(0,Math.min(LANES-1,player.lane+d)); if(next!==player.lane){ player.lane=next; player.targetX=laneX(next,player.w); window.ArcadeAudio?.sfx('move'); } }
function driveVert(d){ if(!running) start(); const ny=Math.max(MIN_Y,Math.min(MAX_Y,player.targetY+d*STEP_Y)); if(ny!==player.targetY){ player.targetY=ny; window.ArcadeAudio?.sfx('move'); } }
function spawn(){ let lane=Math.floor(Math.random()*LANES); let type=Math.random()<.25?'cone':'car'; let w=type==='cone'?48:70, h=type==='cone'?55:104; obstacles.push({lane,x:laneX(lane,w),y:-h-20,w,h,type,color:['#ff5f57','#5ac8fa','#ffd166','#b084ff'][Math.floor(Math.random()*4)]}); if(distance>250&&Math.random()<.22){ let lane2=(lane+1+Math.floor(Math.random()*(LANES-1)))%LANES; obstacles.push({lane:lane2,x:laneX(lane2,66),y:-220,w:66,h:96,type:'car',color:'#62e6a7'}); } }
function hit(a,b){ return a.x+10<b.x+b.w-8&&a.x+a.w-10>b.x+8&&a.y+12<b.y+b.h-8&&a.y+a.h-8>b.y+8; }
function over(){ running=false; const final=Math.floor(distance); best=Math.max(best,final); localStorage.setItem('arcade_best_racing',best); bestEl.textContent=best; window.ArcadeAudio?.sfx('crash'); ovT.textContent='Va chạm!'; ovX.textContent=`Bạn đi được ${final} m • Kỷ lục: ${best} m`; btn.textContent='Chơi lại'; ov.classList.remove('hidden'); window.ArcadeLeaderboard?.show('racing',final,{title:'Road Rush',suffix:' m'}); }
function loop(t){ if(!running) return; const dt=Math.min(.033,(t-last)/1000); last=t; distance+=dt*22; worldSpeed=Math.min(560,270+distance*.55); roadOffset=(roadOffset+worldSpeed*dt)%95; spawnT-=dt; const spawnGap=Math.max(.55,1.15-distance/1400); if(spawnT<=0){ spawn(); spawnT=spawnGap+Math.random()*.42; } player.x+=(player.targetX-player.x)*Math.min(1,dt*13); player.y+=(player.targetY-player.y)*Math.min(1,dt*13); obstacles.forEach(o=>o.y+=worldSpeed*dt); obstacles=obstacles.filter(o=>o.y<c.height+140); for(const o of obstacles) if(hit(player,o)) return over(); scoreEl.textContent=Math.floor(distance); speedEl.textContent=(worldSpeed/270).toFixed(1)+'×'; draw(); requestAnimationFrame(loop); }
function roundRect(px,py,w,h,r,fill){ g.fillStyle=fill; g.beginPath(); g.roundRect(px,py,w,h,r); g.fill(); }
function drawCar(o,playerCar=false){ const s=skin(); roundRect(o.x,o.y,o.w,o.h,13,playerCar?s.player:o.color); g.fillStyle=playerCar?s.glass:'#dff4ff'; g.fillRect(o.x+12,o.y+18,o.w-24,20); g.fillRect(o.x+12,o.y+o.h-38,o.w-24,17); g.fillStyle='#111827'; g.fillRect(o.x-4,o.y+18,7,25); g.fillRect(o.x+o.w-3,o.y+18,7,25); g.fillRect(o.x-4,o.y+o.h-43,7,25); g.fillRect(o.x+o.w-3,o.y+o.h-43,7,25); if(playerCar){ g.fillStyle=s.light; g.fillRect(o.x+8,o.y+4,14,6); g.fillRect(o.x+o.w-22,o.y+4,14,6); } }
function draw(){ g.fillStyle='#143222'; g.fillRect(0,0,c.width,c.height); g.fillStyle='#262a31'; g.fillRect(roadX,0,roadW,c.height); g.fillStyle='#ece7d8'; g.fillRect(roadX-8,0,8,c.height); g.fillRect(roadX+roadW,0,8,c.height); for(let l=1;l<LANES;l++){ let xx=roadX+l*laneW; for(let y=-95+roadOffset;y<c.height;y+=95){ g.fillStyle='rgba(255,255,255,.72)'; g.fillRect(xx-3,y,6,52); } } for(let y=-45+(roadOffset*.6)%70;y<c.height;y+=70){ g.fillStyle='rgba(255,255,255,.08)'; g.fillRect(18,y,52,4); g.fillRect(650,y,52,4); } obstacles.forEach(o=>{ if(o.type==='cone'){ g.fillStyle='#ff8a34'; g.beginPath(); g.moveTo(o.x+o.w/2,o.y); g.lineTo(o.x+o.w,o.y+o.h); g.lineTo(o.x,o.y+o.h); g.closePath(); g.fill(); g.fillStyle='white'; g.fillRect(o.x+9,o.y+30,o.w-18,7); } else drawCar(o); }); drawCar({...player},true); g.fillStyle='rgba(255,255,255,.10)'; g.fillRect(roadX+8,MIN_Y-6,roadW-16,MAX_Y-MIN_Y+player.h+12); g.strokeStyle='rgba(255,255,255,.14)'; g.strokeRect(roadX+8,MIN_Y-6,roadW-16,MAX_Y-MIN_Y+player.h+12); }
document.addEventListener('keydown',e=>{ let k=e.key.toLowerCase(); if(['arrowleft','arrowright','arrowup','arrowdown','a','d','w','s','r'].includes(k)) e.preventDefault(); if(k==='arrowleft'||k==='a') driveHoriz(-1); if(k==='arrowright'||k==='d') driveHoriz(1); if(k==='arrowup'||k==='w') driveVert(-1); if(k==='arrowdown'||k==='s') driveVert(1); if(k==='r') restart(); },{passive:false});
document.querySelectorAll('[data-drive]').forEach(b=>b.addEventListener('pointerdown',e=>{ e.preventDefault(); const d=b.dataset.drive; if(d==='left') driveHoriz(-1); if(d==='right') driveHoriz(1); if(d==='up') driveVert(-1); if(d==='down') driveVert(1); }));
c.addEventListener('pointerdown',e=>{ const r=c.getBoundingClientRect(), px=(e.clientX-r.left)/r.width*c.width, py=(e.clientY-r.top)/r.height*c.height; if(Math.abs(px-player.x)<110&&Math.abs(py-player.y)<130){ if(py<player.y) driveVert(-1); else driveVert(1); } else driveHoriz(px<c.width/2?-1:1); });
window.addEventListener('arcade-skin-change', e=>{ if(e.detail.gameId==='racing') draw(); });
btn.onclick=()=>ovT.textContent==='Va chạm!'?restart():start(); reset();
