const c=document.getElementById('game'),g=c.getContext('2d'),scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),ov=document.getElementById('overlay'),ovT=document.getElementById('ovTitle'),ovX=document.getElementById('ovText'),btn=document.getElementById('startBtn');
let bird,pipes,score,best=+(localStorage.getItem('arcade_best_flap')||0),running=false,last=0,spawnT=0,speed=185;bestEl.textContent=best;
function reset(){bird={x:150,y:250,vy:0,r:16};pipes=[];score=0;spawnT=0;speed=185;scoreEl.textContent=0;draw()}
function start(){if(!running){running=true;window.ArcadeAudio?.startMusic();last=performance.now();ov.classList.add('hidden');requestAnimationFrame(loop)}}
function restart(){running=false;reset();start()}
function flap(){if(!running)start();bird.vy=-330;window.ArcadeAudio?.sfx('flap')}
function spawn(){let gap=Math.max(118,155-score*1.2),top=60+Math.random()*(c.height-gap-140);pipes.push({x:c.width+35,w:66,top,gap,passed:false})}
function over(){running=false;best=Math.max(best,score);localStorage.setItem('arcade_best_flap',best);bestEl.textContent=best;window.ArcadeAudio?.sfx('gameover');ovT.textContent='Game Over';ovX.textContent=`Bạn vượt ${score} cặp cột. Kỷ lục: ${best}.`;btn.textContent='Chơi lại';ov.classList.remove('hidden');window.ArcadeLeaderboard?.show('sky-flap',score,{title:'Sky Flap'})}
function loop(t){if(!running)return;let dt=Math.min(.033,(t-last)/1000);last=t;spawnT+=dt;speed=Math.min(300,185+score*4);if(spawnT>1.45){spawnT=0;spawn()}bird.vy+=950*dt;bird.y+=bird.vy*dt;pipes.forEach(p=>p.x-=speed*dt);pipes=pipes.filter(p=>p.x+p.w>-20);for(const p of pipes){if(!p.passed&&p.x+p.w<bird.x){p.passed=true;score++;scoreEl.textContent=score;window.ArcadeAudio?.sfx('point')}if(bird.x+bird.r>p.x&&bird.x-bird.r<p.x+p.w&&(bird.y-bird.r<p.top||bird.y+bird.r>p.top+p.gap))return over()}if(bird.y+bird.r>c.height-24||bird.y-bird.r<0)return over();draw();requestAnimationFrame(loop)}
function draw(){let sky=g.createLinearGradient(0,0,0,c.height);sky.addColorStop(0,'#163b68');sky.addColorStop(1,'#7ec8ef');g.fillStyle=sky;g.fillRect(0,0,c.width,c.height);g.fillStyle='rgba(255,255,255,.34)';for(let i=0;i<6;i++){let x=(i*157+70)%c.width,y=55+(i%3)*75;g.beginPath();g.ellipse(x,y,46,15,0,0,Math.PI*2);g.fill()}for(const p of pipes){g.fillStyle='#43bf6f';g.fillRect(p.x,0,p.w,p.top);g.fillRect(p.x,p.top+p.gap,p.w,c.height-(p.top+p.gap)-24);g.fillStyle='#7be89a';g.fillRect(p.x-6,p.top-18,p.w+12,18);g.fillRect(p.x-6,p.top+p.gap,p.w+12,18)}g.fillStyle='#d7b46a';g.fillRect(0,c.height-24,c.width,24);g.save();g.translate(bird.x,bird.y);g.rotate(Math.max(-.45,Math.min(.65,bird.vy/650)));g.fillStyle='#ffd45c';g.beginPath();g.arc(0,0,bird.r,0,Math.PI*2);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(6,-5,5,0,Math.PI*2);g.fill();g.fillStyle='#1d2533';g.beginPath();g.arc(7,-5,2,0,Math.PI*2);g.fill();g.fillStyle='#ff8c42';g.beginPath();g.moveTo(14,0);g.lineTo(27,5);g.lineTo(14,9);g.closePath();g.fill();g.restore()}
document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();flap()}if(e.key.toLowerCase()==='r')restart()},{passive:false});c.addEventListener('pointerdown',e=>{e.preventDefault();flap()});btn.onclick=()=>ovT.textContent==='Game Over'?restart():start();reset();
