const c=document.getElementById('game'),g=c.getContext('2d');
const scoreEl=document.getElementById('score'),crossEl=document.getElementById('crossings'),bestEl=document.getElementById('best');
const ov=document.getElementById('overlay'),ovT=document.getElementById('ovTitle'),ovX=document.getElementById('ovText'),btn=document.getElementById('startBtn');
const COLS=12,ROWS=10,CELL=65, lanes=[1,2,3,4,5,6,7,8];
let chicken,cars,score,crossings,best=+(localStorage.getItem('arcade_best_chicken')||0),running=false,last=0,touchStart=null;
bestEl.textContent=best;
const laneCfg=[
  {dir:1,speed:125,gap:245,color:'#5ac8fa'}, {dir:-1,speed:155,gap:280,color:'#ff6b6b'},
  {dir:1,speed:190,gap:330,color:'#ffd166'}, {dir:-1,speed:135,gap:260,color:'#b084ff'},
  {dir:1,speed:175,gap:300,color:'#62e6a7'}, {dir:-1,speed:215,gap:360,color:'#ff9f43'},
  {dir:1,speed:145,gap:250,color:'#ff77aa'}, {dir:-1,speed:185,gap:320,color:'#84a9ff'}
];
function reset(){chicken={col:5,row:9};score=0;crossings=0;cars=[];laneCfg.forEach((cfg,i)=>{for(let x=-cfg.gap;x<c.width+cfg.gap;x+=cfg.gap){cars.push({lane:i,row:lanes[i],x:x+(i%2)*110,w:80+(i%3)*12,h:42,cfg})}});scoreEl.textContent=0;crossEl.textContent=0;draw()}
function start(){if(running)return;running=true;window.ArcadeAudio?.startMusic();last=performance.now();ov.classList.add('hidden');requestAnimationFrame(loop)}
function restart(){running=false;reset();start()}
function move(dx,dy){if(!running)start();const nc=Math.max(0,Math.min(COLS-1,chicken.col+dx)),nr=Math.max(0,Math.min(ROWS-1,chicken.row+dy));if(nc===chicken.col&&nr===chicken.row)return;chicken.col=nc;chicken.row=nr;if(dy<0)score+=2;window.ArcadeAudio?.sfx('move');if(chicken.row===0){crossings++;score+=100;crossEl.textContent=crossings;window.ArcadeAudio?.sfx('win');chicken={col:5,row:9}}scoreEl.textContent=score}
function chickenRect(){return{x:chicken.col*CELL+16,y:chicken.row*CELL+13,w:33,h:39}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function over(){running=false;best=Math.max(best,score);localStorage.setItem('arcade_best_chicken',best);bestEl.textContent=best;window.ArcadeAudio?.sfx('crash');ovT.textContent='Ôi! Gà bị tông';ovX.textContent=`Điểm: ${score} • Qua đường: ${crossings} lần • Kỷ lục: ${best}`;btn.textContent='Chơi lại';ov.classList.remove('hidden');window.ArcadeLeaderboard?.show('chicken-crossing',score,{title:'Chicken Crossing'})}
function loop(t){if(!running)return;const dt=Math.min(.033,(t-last)/1000);last=t;const multi=1+crossings*.12;for(const car of cars){car.x+=car.cfg.dir*car.cfg.speed*multi*dt;if(car.cfg.dir>0&&car.x>c.width+100)car.x=-car.w-120;if(car.cfg.dir<0&&car.x+car.w<-100)car.x=c.width+120}const cr=chickenRect();for(const car of cars){const y=car.row*CELL+(CELL-car.h)/2;if(car.row===chicken.row&&hit(cr,{x:car.x,y,w:car.w,h:car.h}))return over()}draw();requestAnimationFrame(loop)}
function draw(){for(let r=0;r<ROWS;r++){if(r===0||r===9){g.fillStyle=r===0?'#2f8d52':'#3c9b59'}else{g.fillStyle=r%2?'#30343b':'#292e35'}g.fillRect(0,r*CELL,c.width,CELL);if(r>0&&r<9){g.strokeStyle='rgba(255,255,255,.18)';g.setLineDash([26,22]);g.beginPath();g.moveTo(0,r*CELL);g.lineTo(c.width,r*CELL);g.stroke();g.setLineDash([])}}g.fillStyle='rgba(255,255,255,.16)';for(let x=20;x<c.width;x+=90){g.beginPath();g.arc(x,28,4,0,Math.PI*2);g.fill();g.beginPath();g.arc(x+38,c.height-25,4,0,Math.PI*2);g.fill()}for(const car of cars){const y=car.row*CELL+(CELL-car.h)/2;g.fillStyle=car.cfg.color;g.beginPath();g.roundRect(car.x,y,car.w,car.h,10);g.fill();g.fillStyle='#cfeeff';g.fillRect(car.x+14,y+7,car.w-28,10);g.fillStyle='#10151e';g.fillRect(car.x+10,y+car.h-5,16,8);g.fillRect(car.x+car.w-26,y+car.h-5,16,8)}const cr=chickenRect();g.save();g.translate(cr.x+cr.w/2,cr.y+cr.h/2);g.fillStyle='#fff4d6';g.beginPath();g.arc(0,3,16,0,Math.PI*2);g.fill();g.fillStyle='#fff';g.beginPath();g.arc(7,-10,10,0,Math.PI*2);g.fill();g.fillStyle='#ef3f45';g.beginPath();g.arc(4,-21,4,0,Math.PI*2);g.arc(10,-20,4,0,Math.PI*2);g.fill();g.fillStyle='#ffb33a';g.beginPath();g.moveTo(16,-10);g.lineTo(27,-6);g.lineTo(16,-3);g.closePath();g.fill();g.fillStyle='#172033';g.beginPath();g.arc(10,-12,2,0,Math.PI*2);g.fill();g.restore()}
function dir(name){if(name==='up')move(0,-1);if(name==='down')move(0,1);if(name==='left')move(-1,0);if(name==='right')move(1,0)}
document.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','r'].includes(k))e.preventDefault();if(k==='arrowup'||k==='w')dir('up');if(k==='arrowdown'||k==='s')dir('down');if(k==='arrowleft'||k==='a')dir('left');if(k==='arrowright'||k==='d')dir('right');if(k==='r')restart()},{passive:false});
document.querySelectorAll('[data-move]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();dir(b.dataset.move)}));
c.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});c.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<18)return;if(Math.abs(dx)>Math.abs(dy))dir(dx>0?'right':'left');else dir(dy>0?'down':'up')},{passive:true});
btn.onclick=()=>ovT.textContent.includes('tông')?restart():start();reset();
