const c=document.getElementById('game'),x=c.getContext('2d'),S=30,C=c.width/S,scoreEl=document.getElementById('score'),bestEl=document.getElementById('best'),ov=document.getElementById('overlay'),ovT=document.getElementById('ovTitle'),ovX=document.getElementById('ovText'),startBtn=document.getElementById('startBtn');
let snake,food,dir,next,score=0,best=+(localStorage.getItem('arcade_best_snake')||0),run=false,pause=false,timer,delay=120;bestEl.textContent=best;
function reset(){snake=[{x:14,y:15},{x:13,y:15},{x:12,y:15},{x:11,y:15}];dir=next={x:1,y:0};score=0;delay=120;spawn();hud();draw();}
function spawn(){do{food={x:Math.floor(Math.random()*S),y:Math.floor(Math.random()*S)}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}
function hud(){scoreEl.textContent=score;bestEl.textContent=best}
function start(){clearTimeout(timer);if(!run){run=true;pause=false;window.ArcadeAudio?.startMusic();ov.classList.add('hidden');tickSoon()}}
function restart(){clearTimeout(timer);reset();run=true;pause=false;ov.classList.add('hidden');tickSoon()}
function tickSoon(){if(run&&!pause)timer=setTimeout(tick,delay)}
function tick(){dir=next;let h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.x>=S||h.y<0||h.y>=S||snake.some((p,i)=>i<snake.length-1&&p.x===h.x&&p.y===h.y))return over();snake.unshift(h);if(h.x===food.x&&h.y===food.y){score+=10;best=Math.max(best,score);localStorage.setItem('arcade_best_snake',best);delay=Math.max(55,120-Math.floor(score/40)*6);window.ArcadeAudio?.sfx('eat');spawn()}else snake.pop();hud();draw();tickSoon()}
function over(){run=false;clearTimeout(timer);window.ArcadeAudio?.sfx('gameover');ovT.textContent='Game Over';ovX.textContent=`Điểm: ${score} • Kỷ lục: ${best}`;startBtn.textContent='Chơi lại';ov.classList.remove('hidden');window.ArcadeLeaderboard?.show('snake',score,{title:'Neon Snake'})}
function toggle(){if(!run)return;pause=!pause;clearTimeout(timer);if(pause){ovT.textContent='Tạm dừng';ovX.textContent='Nhấn P hoặc nút tiếp tục.';startBtn.textContent='Tiếp tục';ov.classList.remove('hidden')}else{ov.classList.add('hidden');tickSoon()}}
function setDir(dx,dy){if(!run)start();if(dx===-dir.x&&dy===-dir.y)return;next={x:dx,y:dy}}
function draw(){x.fillStyle='#07110c';x.fillRect(0,0,c.width,c.height);x.strokeStyle='rgba(120,180,145,.08)';for(let i=1;i<S;i++){let p=i*C;x.beginPath();x.moveTo(p,0);x.lineTo(p,c.height);x.stroke();x.beginPath();x.moveTo(0,p);x.lineTo(c.width,p);x.stroke()}let fx=food.x*C+C/2,fy=food.y*C+C/2;x.shadowColor='#ff6680';x.shadowBlur=16;x.fillStyle='#ff6680';x.beginPath();x.arc(fx,fy,7,0,Math.PI*2);x.fill();x.shadowBlur=0;snake.forEach((p,i)=>{x.fillStyle=i?'#3de27c':'#9cffbf';x.beginPath();x.roundRect(p.x*C+3,p.y*C+3,C-6,C-6,6);x.fill()})}
document.addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','p','r',' '].includes(k))e.preventDefault();if(k==='arrowup'||k==='w')setDir(0,-1);if(k==='arrowdown'||k==='s')setDir(0,1);if(k==='arrowleft'||k==='a')setDir(-1,0);if(k==='arrowright'||k==='d')setDir(1,0);if(k==='p'||k===' ')toggle();if(k==='r')restart()},{passive:false});
document.querySelectorAll('[data-dir]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();let d=b.dataset.dir;if(d==='up')setDir(0,-1);if(d==='down')setDir(0,1);if(d==='left')setDir(-1,0);if(d==='right')setDir(1,0)}));startBtn.onclick=()=>run&&pause?toggle():ovT.textContent==='Game Over'?restart():start();reset();
